package com.example.network
import android.content.Context
import android.net.wifi.WifiManager
import android.text.format.Formatter
import java.io.IOException
import java.net.*
import kotlin.math.pow
object NetworkUtils {
    val standardPorts = mapOf(21 to "FTP",22 to "SSH",23 to "Telnet",25 to "SMTP",53 to "DNS",80 to "HTTP",110 to "POP3",135 to "RPC",139 to "NetBIOS",143 to "IMAP",443 to "HTTPS",445 to "SMB",1433 to "MSSQL",3306 to "MySQL",3389 to "RDP",5432 to "PostgreSQL",8080 to "HTTP-Alt",8443 to "HTTPS-Alt")
    private val vendorOuiDb = mapOf("00:11:2F" to "Asustek","00:18:39" to "Cisco","00:1D:0F" to "TP-Link","10:FE:ED" to "TP-Link","14:CC:20" to "TP-Link","50:C7:BF" to "TP-Link","00:19:66" to "D-Link","00:21:91" to "D-Link","84:C9:B2" to "D-Link","00:1C:DF" to "Belkin","00:17:3F" to "Linksys","00:1A:2B" to "Apple","B0:35:B2" to "Apple","00:15:99" to "Samsung","00:1E:c9" to "Dell","14:18:77" to "Dell")
    fun getVendor(mac: String?): String { if (mac.isNullOrEmpty()) return "Unknown"; val clean = mac.replace("-",":").uppercase(); if (clean.length>=8) vendorOuiDb[clean.substring(0,8)]?.let { return it }; return "Generic Device" }
    fun getLocalIpAddress(context: Context): String { val wm = context.applicationContext.getSystemService(Context.WIFI_SERVICE) as? WifiManager; return Formatter.formatIpAddress(wm?.connectionInfo?.ipAddress ?: 0) }
    fun getGatewayAddress(context: Context): String { val wm = context.applicationContext.getSystemService(Context.WIFI_SERVICE) as? WifiManager; return Formatter.formatIpAddress(wm?.dhcpInfo?.gateway ?: 0) }
    fun getWifiSsid(context: Context): String { val wm = context.applicationContext.getSystemService(Context.WIFI_SERVICE) as? WifiManager; val s = wm?.connectionInfo?.ssid ?: "N/A"; return if (s.startsWith("\"") && s.endsWith("\"")) s.substring(1,s.length-1) else s }
    fun getWifiBssid(context: Context): String { val wm = context.applicationContext.getSystemService(Context.WIFI_SERVICE) as? WifiManager; return wm?.connectionInfo?.bssid ?: "00:00:00:00:00:00" }
    fun getWifiLinkSpeed(context: Context): Int { val wm = context.applicationContext.getSystemService(Context.WIFI_SERVICE) as? WifiManager; return wm?.connectionInfo?.linkSpeed ?: 0 }
    fun getWifiFrequency(context: Context): Int { val wm = context.applicationContext.getSystemService(Context.WIFI_SERVICE) as? WifiManager; return wm?.connectionInfo?.frequency ?: 2412 }
    fun getWifiRssiDbm(context: Context): Int { val wm = context.applicationContext.getSystemService(Context.WIFI_SERVICE) as? WifiManager; return wm?.connectionInfo?.rssi ?: -100 }
    fun tryConnectPort(ip: String, port: Int, timeoutMs: Int = 120): Long? { val t = System.currentTimeMillis(); var s: Socket? = null; return try { s = Socket(); s.connect(InetSocketAddress(ip,port),timeoutMs); System.currentTimeMillis()-t } catch(e:Exception){null} finally { try{s?.close()}catch(_:IOException){} } }
    fun pingHost(ip: String, timeoutMs: Int = 150): Long? { return try { val a = InetAddress.getByName(ip); if (a.isReachable(timeoutMs)) return System.currentTimeMillis().let{it}; tryConnectPort(ip,80,timeoutMs) ?: tryConnectPort(ip,443,timeoutMs) ?: tryConnectPort(ip,22,timeoutMs) } catch(e:Exception){null} }
    fun computeWpsPinDlink(bssid: String): String { val mac=bssid.replace(":","").uppercase(); if(mac.length<12) return "12345670"; val v=mac.substring(mac.length-6).toLongOrNull(16)?:1234567L; val p=((v%10000000).toString().padStart(7,'0')); return "$p${calcChecksum(p.toLong())}" }
    fun computeWpsPinAsus(bssid: String): String { val mac=bssid.replace(":","").uppercase(); if(mac.length<12) return "25442544"; val v=mac.substring(mac.length-4).toLongOrNull(16)?:2542L; val p=(((v*17)%10000000).toString().padStart(7,'0')); return "$p${calcChecksum(p.toLong())}" }
    fun computeWpsPinBelkin(bssid: String): String { val mac=bssid.replace(":","").uppercase(); if(mac.length<12) return "11111117"; val v=mac.substring(mac.length-4).toLongOrNull(16)?:9991L; val p=(((v+12345)%10000000).toString().padStart(7,'0')); return "$p${calcChecksum(p.toLong())}" }
    fun computeWpsPinArcadyan(bssid: String): String { val mac=bssid.replace(":","").uppercase(); if(mac.length<12) return "00000000"; val v=mac.substring(mac.length-3).toLongOrNull(16)?:111L; val p=(((v*11)%10000000).toString().padStart(7,'0')); return "$p${calcChecksum(p.toLong())}" }
    private fun calcChecksum(pin: Long): Long { var a=0L; var t=pin; a+=3*(t%10);t/=10;a+=1*(t%10);t/=10;a+=3*(t%10);t/=10;a+=1*(t%10);t/=10;a+=3*(t%10);t/=10;a+=1*(t%10);t/=10;a+=3*(t%10); return (10-(a%10))%10 }
    fun sendWakeOnLan(macAddress: String, targetIp: String="255.255.255.255"): Boolean { return try { val mb=macAddress.split(":","-").map{it.toInt(16).toByte()}.toByteArray(); if(mb.size!=6) return false; val b=ByteArray(6+16*mb.size); for(i in 0 until 6) b[i]=0xff.toByte(); for(i in 1..16) System.arraycopy(mb,0,b,i*6,mb.size); val s=DatagramSocket(); s.broadcast=true; s.send(DatagramPacket(b,b.size,InetAddress.getByName(targetIp),9)); s.close(); true } catch(e:Exception){false} }
    fun calculateCidrDetails(inputCidr: String): CidrResult { try { val p=inputCidr.split("/"); if(p.size!=2) return CidrResult(errorMessage="Bad CIDR"); val maskBits=p[1].toIntOrNull()?:return CidrResult(errorMessage="Bad mask"); if(maskBits<0||maskBits>32) return CidrResult(errorMessage="Mask 0-32"); val ipBytes=InetAddress.getByName(p[0]).address; var ipInt=0; for(b in ipBytes) ipInt=(ipInt shl 8)or(b.toInt() and 0xff); val mask=if(maskBits==0) 0 else (-1 shl (32-maskBits)); val net=ipInt and mask; val bcast=ipInt or mask.inv(); val hostCount=if(maskBits==32) 1 else if(maskBits==31) 2 else (2.0.pow(32-maskBits)-2).toInt(); return CidrResult(networkIp=intToIp(net),broadcastIp=intToIp(bcast),netmask=intToIp(mask),hostsNum=hostCount,rangeIp="${intToIp(net+1)} - ${intToIp(bcast-1)}",isSuccess=true) } catch(e:Exception){return CidrResult(errorMessage=e.message)} }
    private fun intToIp(ip: Int) = "${(ip shr 24)and 0xFF}.${(ip shr 16)and 0xFF}.${(ip shr 8)and 0xFF}.${ip and 0xFF}"
    data class CidrResult(val networkIp:String="N/A",val broadcastIp:String="N/A",val netmask:String="N/A",val hostsNum:Int=0,val rangeIp:String="N/A",val isSuccess:Boolean=false,val errorMessage:String?=null)
}
